### PR TITLE
Update 7 FileManipulation

### PR DESCRIPTION
**Pull request by kareman**
Hi, just updated this file to work with Xcode 7 beta 6 and simplified the error handling code.

### CODE REVIEW

**Comment by blakemerryman** [comment]
Thanks for the pull request! A few things:
- To my knowledge, `stringByAppendingPathComponent:` has not be deprecated, though I really do like your implementation. Much cleaner & Swift-like.
- Unfortunately, your code does not work. I get the following error when running:

``` bash
blake-Intro Examples$ chmod +x 7-FileManipulation.swift 
blake-Intro Examples$ ./7-FileManipulation.swift 
./7-FileManipulation.swift:5:98: error: consecutive statements on a line must be separated by ';'
let ddFolderPath = NSHomeDirectoryForUser(NSUserName())! + "/Library/Developer/Xcode/DerivedData")
                                                                                                 ^
```

Should be

``` swift
let ddFolderPath = NSHomeDirectoryForUser(NSUserName())! + "/Library/Developer/Xcode/DerivedData"
```

If you fix the typo and resubmit, I'll merge. Thanks again!

**Comment by kareman** [comment]
Sorry about that, it should work now.

**Comment by kareman** [comment]
Regarding stringByAppendingPathComponent, deprecated was the wrong word. According to Swift it has been marked unavailable (using Xcode 7 beta 6):

```
7-FileManipulation.swift:5:58: error: 'stringByAppendingPathComponent' is unavailable: Use URLByAppendingPathComponent on NSURL instead.
let ddFolderPath = NSHomeDirectoryForUser(NSUserName())!.stringByAppendingPathComponent("Library/Developer/Xcode/DerivedData")
                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Foundation.String:352:8: note: 'stringByAppendingPathComponent' has been explicitly marked unavailable here
  func stringByAppendingPathComponent(aString: String) -> String
       ^

```

**Comment by blakemerryman** [comment]
Thanks for the pull request. Feel free to submit your own utility scripts to the "Utility Scripts" folder. Would love to have a nice little collection. Been very busy since I started this project.

**Pull request merged**
